# Generated by Django 2.2.13 on 2021-04-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0114_remove_org_registrant'),
        ('judge', '0114_custom_checker_uploader'),
    ]

    operations = [
    ]
