# Generated by Django 2.2.13 on 2021-04-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0115_contest_scoreboard_visibility'),
        ('judge', '0115_auto_20210410_1426'),
    ]

    operations = [
    ]
