# Generated by Django 2.2.19 on 2021-04-20 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0114_custom_checker_uploader'),
        ('judge', '0115_contest_scoreboard_visibility'),
    ]

    operations = [
    ]
