# Generated by Django 2.2.19 on 2021-05-08 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0116_merge_20210420_0758'),
        ('judge', '0116_contest_curator_and_tester'),
    ]

    operations = [
    ]
