# Generated by Django 2.2.19 on 2021-05-09 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0118_convert_to_dates'),
        ('judge', '0117_merge_20210508_1434'),
    ]

    operations = [
    ]
