# Generated by Django 3.2.16 on 2022-12-21 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0134_add_voting_functionality'),
        ('judge', '0134_alter_profile_timezone'),
    ]

    operations = [
    ]
