# Generated by Django 3.2.16 on 2022-12-30 10:50

from django.db import migrations
import django.core.validators
from django.db import models
import django.db.models.deletion
import judge.models.problem_data
import judge.models.profile
import judge.utils.problem_data

class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0137_alter_problempointsvote_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemdata',
            name='checker',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('floats', 'Floats'), ('floatsabs', 'Floats (absolute)'), ('floatsrel', 'Floats (relative)'), ('rstripped', 'Non-trailing spaces'), ('sorted', 'Unordered'), ('identical', 'Byte identical'), ('linecount', 'Line-by-line'), ('custom_py', 'Customer checker (Python)'), ('custom_cpp', 'Customer checker (CPP)')], max_length=10, verbose_name='checker'),
        ),
        migrations.AlterField(
            model_name='problemdata',
            name='custom_checker',
            field=models.FileField(blank=True, null=True, storage=judge.utils.problem_data.ProblemDataStorage(), upload_to=judge.models.problem_data.problem_directory_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py', 'cpp'])], verbose_name='checker file'),
        ),
        migrations.AlterField(
            model_name='problemtestcase',
            name='checker',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('floats', 'Floats'), ('floatsabs', 'Floats (absolute)'), ('floatsrel', 'Floats (relative)'), ('rstripped', 'Non-trailing spaces'), ('sorted', 'Unordered'), ('identical', 'Byte identical'), ('linecount', 'Line-by-line'), ('custom_py', 'Customer checker (Python)'), ('custom_cpp', 'Customer checker (CPP)')], max_length=10, verbose_name='checker'),
        ),
    ]